source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'
use_frameworks!
inhibit_all_warnings!

def shared_pods
    pod 'ReSwift'
end

target 'LittleOrion' do
    shared_pods
end

target 'OrionTests' do
  shared_pods
end
