source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

def shared_pods
    pod 'ReSwift', :git => 'https://github.com/ReSwift/ReSwift', :branch => 'benji/skip-repeats-prototype'
end

target 'LittleOrion' do
    shared_pods
end